# --- Local Development Configuration ---

spring.datasource.url=jdbc:postgresql://localhost:5432/harmos-db
spring.datasource.username=harmos-db-owner
spring.datasource.password=j17DgpslK
spring.jpa.hibernate.ddl-auto=create-drop
