# Configuración de Cloudinary
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:hwhkb6um4}
  api-key: ${CLOUDINARY_API_KEY:865466632331663}
  api-secret: ${CLOUDINARY_API_SECRET:Gn4qNjMGA6uWQbW8Qr0QyIDyIew}

# Configuración para subida de archivos
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

# URL del frontend (cambiar por tu URL real)
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000} 