# PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=true

# API prefix
server.servlet.context-path=/api
server.port=${PORT:8080}
