# PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=true

# API prefix
server.servlet.context-path=/api
server.port=${PORT:8080}

# Email Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL
app.frontend.url=${FRONTEND_URL:https://harmos-web-0d62e723abba.herokuapp.com}

# Database Repopulation
app.database.repopulate=true
