# --- Local Development Configuration ---

spring.datasource.url=jdbc:postgresql://localhost:5432/harmos-db
spring.datasource.username=harmos-db-owner
spring.datasource.password=j17DgpslK
spring.jpa.hibernate.ddl-auto=update

# Email Configuration
spring.mail.username=noreplyharmos@gmail.com
spring.mail.password=crcb vkfs qiia ifcn
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL for local development
app.frontend.url=http://localhost:3000
